### NumPy

NumPy is a findamental library for scientific computing in Python. It provides support for arrays and marrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy


In [2]:
!pip install --upgrade pip

In [3]:
import numpy as np

# Create array using numpy
# Create a 1D array

arr1=np.array([1,2,3,4,5]) 
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# Two dimension
arr2=np.array([1,2,3,4,5]) 
arr2.reshape(1,5) # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2=np.array([[1,2,3,4,5], [5,6,7,8,9]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Attributes of numpy
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # (2,3)
print("Number of dimensions:", arr.ndim) # 2
print("Size (number of elements):", arr.size) # 6
print("Data type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size(in bytes): 8


In [10]:
# NumPy ectorized Operation

arr1=np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element Wise Addition
print("Addition:", arr1+arr2)

# Element Wise Substraction
print("Subtraction:", arr1-arr2)

# Element Wise Multiplication
print("Multiplication:", arr1 * arr2)

# Element Wise Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [11]:
# Universal Function
arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
#array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [14]:
arr[0][0]
print(arr[0:2, 1:])

[[2 3 4]
 [6 7 8]]


In [15]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [17]:
# Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [18]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [19]:
# Statistical Concepts - Normalization 
# Have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and std 
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean 
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation 
std = np.std(data)
print("Standard Deviation:", std)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [21]:
# Logical Operation 
data=np.array([1,2,3,4,5,6,7,8,9,10])

data >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
data[(data>5) & (data<=8)] use logical AND 

SyntaxError: invalid syntax (3710548605.py, line 1)