# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np 

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20
array=np.random.randint(1,21, size=(5,5))
print("Original Array: ")
print(array)

# Replace all the elements in the third column with 1.
array[:, 2] =1
print("Replaced Array:")
print(array)



Original Array: 
[[ 2  3 12 16  6]
 [10  5  3 13  9]
 [16 13  5  6  5]
 [17  8 13  4 14]
 [19  2  4  1  8]]
Replaced Array:
[[ 2  3  1 16  6]
 [10  5  1 13  9]
 [16 13  1  6  5]
 [17  8  1  4 14]
 [19  2  1  1  8]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
array = np.arange(1, 17).reshape((4, 4))
print("Original:")
print(array)

np.fill_diagonal(array, 0)
print("Replace:")
print(array)

Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Replace:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [7]:
array=np.arange(1,37).reshape((6,6))
print("Original:")
print(array)

# Extract the sub-array consisiting of the 3rd to 5th rows and 2nd to 4th columns
sub_array=array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [10]:
array=np.random.randint(1,21, size=(5,5))
print("Original:")
print(array)

# Elements on the border
border_elements= np.concatenate((array[0, :], array[-1, : ], array[1:-1, 0], array[1:-1, -1])) # First two will give first row and last row
print("Border Elements:")
print(border_elements)

Original:
[[ 5 12 18 11 19]
 [15 19  1 15 10]
 [13 20 11  3  1]
 [ 9  6 12  5  9]
 [20  1 18  5  6]]
Border Elements:
[ 5 12 18 11 19 20  1 18  5  6 15 13  9 10  1  9]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [16]:
array1 = np.random.randint(1,11, size=(3,4))
array2 = np.random.randint(1,11, size=(3,4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Element-Wise Addition 
print("Element-wise Addition: \n", array1+array2)
print("Subtraction: \n", array1-array2)
print("Multiplication: \n", array1*array2)
print("Division: \n", array1/array2)

Array 1:
[[4 9 6 4]
 [7 7 1 7]
 [5 1 8 8]]
Array 2:
[[10  4  3  7]
 [ 2  6  2  2]
 [ 3  4  6  1]]
Element-wise Addition: 
 [[14 13  9 11]
 [ 9 13  3  9]
 [ 8  5 14  9]]
Subtraction: 
 [[-6  5  3 -3]
 [ 5  1 -1  5]
 [ 2 -3  2  7]]
Multiplication: 
 [[40 36 18 28]
 [14 42  2 14]
 [15  4 48  8]]
Division: 
 [[0.4        2.25       2.         0.57142857]
 [3.5        1.16666667 0.5        3.5       ]
 [1.66666667 0.25       1.33333333 8.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [18]:
array= np.arange(1, 17).reshape((4,4))
print("Original Shape:")
print(array)

# Compute row-wise and column-wise sum 
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original Shape:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [22]:
array= np.random.randint(1,21, size=(5,5))
print("Original:")
print(array)

#Compute the mean, median, standard deviation, and variance of the array.
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))
print("Variance:", np.var(array))

Original:
[[19  3  5  8  2]
 [ 4  2 14 10 20]
 [14 12 12 11 10]
 [18 11 17 16  7]
 [ 2 18  3 13 13]]
Mean: 10.56
Median: 11.0
Standard Deviation: 5.692661943238858
Variance: 32.406400000000005


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [26]:
array = np.arange(1,10).reshape((3,3))
print("Original Array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array= (array - mean) / std_dev

print("Normalized Array")
print(normalized_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [29]:
array = np.random.randint(1,10, size=(3,3))
row_array = np.random.randint(1, 10, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[5 1 7]
 [3 2 8]
 [8 5 8]]
1D array:
[5 5 2]
Resulting array:
[[10  6  9]
 [ 8  7 10]
 [13 10 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [31]:
array = np.random.randint(1,10, size=(4,4))
column_array = np.random.randint(1, 10, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[3 8 9 5]
 [4 5 8 8]
 [5 2 1 9]
 [9 4 3 8]]
1D array:
[5 5 2]
Resulting array:
[[ 0  5  6  2]
 [ 3  4  7  7]
 [-4 -7 -8  0]
 [ 6  1  0  5]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [32]:
matrix=np.random.randint(1,11, size=(3,3))
print("Original Matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original Matrix:
[[ 9  4  9]
 [ 1  8 10]
 [ 9 10 10]]
Determinant: -418.0
Inverse:
[[ 0.04784689 -0.11961722  0.07655502]
 [-0.19138756 -0.0215311   0.1937799 ]
 [ 0.14832536  0.1291866  -0.16267943]]
Eigenvalues: [23.88007052  6.02512161 -2.90519213]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [33]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[ 2  4 10]
 [10 10  4]]
Array 2:
[[1 5]
 [5 9]
 [3 2]]
Matrix multiplication result:
[[ 52  66]
 [ 72 148]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [34]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [35]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[ 8  2  5  9 15]
 [12 10  3  6 14]
 [20 17 14  3 15]
 [19 19 11 10  9]
 [ 2  1 17 18 16]]
Flattened array:
[ 8  2  5  9 15 12 10  3  6 14 20 17 14  3 15 19 19 11 10  9  2  1 17 18
 16]
Reshaped array:
[[ 8  2  5  9 15]
 [12 10  3  6 14]
 [20 17 14  3 15]
 [19 19 11 10  9]
 [ 2  1 17 18 16]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [36]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[12 16 12 20 19]
 [ 3 10  4 20  5]
 [17  2 20  1  2]
 [10  8  1  5 20]
 [19  1 10 17 20]]
Corner elements:
[12 19 19 20]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [37]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[19 13  1  7]
 [ 4 13 15 19]
 [ 5 17 19 10]
 [ 1  3  7 17]]
Modified array:
[[10 10  1  7]
 [ 4 10 10 10]
 [ 5 10 10 10]
 [ 1  3  7 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [38]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Angela', 23, 58.2), ('Trevor', 24, 90.3), ('Masaki', 21, 68.7)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Angela', 23, 58.2) ('Trevor', 24, 90.3) ('Masaki', 21, 68.7)]
Sorted array by age:
[('Masaki', 21, 68.7) ('Angela', 23, 58.2) ('Trevor', 24, 90.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [39]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [40]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[20  2 14 10]
 [ 7  6 18 13]
 [15 16 11  9]
 [20 20 19 15]]
Masked array:
[[-- 2 -- 10]
 [7 6 -- --]
 [-- -- -- 9]
 [-- -- -- --]]
Sum of unmasked elements: 34


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [41]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 9 13  3]
 [20 13 12]
 [18 14 14]]
Masked array:
[[-- 13 3]
 [20 -- 12]
 [18 14 --]]
Modified masked array:
[[13 13  3]
 [20 13 12]
 [18 14 13]]
